---

repository:
  name: nocbot-role-homebrew
  description: Ansible role to install Homebrew applications
  homepage: https://vpc.dev
  has_wiki: false

labels:
  - name: bug
    color: CC0000
  - name: feature
    color: 336699

...
