---

- name: Install Homebrew applications
  homebrew:
    name: "{{ item }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop:
    - "{{ homebrew_installed_packages }}"
    - "{{ homebrew_installed_packages_user }}"
  notify:
    - Clear homebrew cache

- name: Ensure blacklisted Homebrew packages are not installed.
  homebrew:
    name: "{{ item }}"
    state: absent
  loop:
    - "{{ homebrew_uninstalled_packages }}"
    - "{{ homebrew_uninstalled_packages_user }}"

- name: Upgrade all Homebrew packages.
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  when: homebrew_upgrade_all_packages
  notify:
    - Clear homebrew cache

...